openapi: 3.0.3
info:
  title: Adhub RAG Bot API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /v1/chat:
    post:
      summary: Ask a question to the RAG bot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message, user]
              properties:
                message: { type: string }
                user:
                  type: object
                  required: [tenant_id]
                  properties:
                    tenant_id: { type: string }
                    role: { type: string }
                    plan: { type: string }
      responses:
        '200':
          description: Bot response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer: { type: string }
                  refusal: { type: boolean }
                  citations:
                    type: array
                    items: { type: integer }
                  chunks_used:
                    type: array
                    items: { type: string }
  /v1/ingest:
    post:
      summary: Ingest documents into the knowledge base
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [docs]
              properties:
                docs:
                  type: array
                  items:
                    type: object
                    required: [tenant_id, content]
                    properties:
                      tenant_id: { type: string }
                      source: { type: string }
                      section: { type: string }
                      doc_type: { type: string }
                      version: { type: string }
                      content: { type: string }
      responses:
        '200':
          description: Ingestion result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  inserted: { type: integer }
